
package com.people.management;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PeopleImpl", targetNamespace = "http://management.people.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PeopleImpl {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "getNameReturn", targetNamespace = "http://management.people.com")
    @RequestWrapper(localName = "getName", targetNamespace = "http://management.people.com", className = "com.people.management.GetName")
    @ResponseWrapper(localName = "getNameResponse", targetNamespace = "http://management.people.com", className = "com.people.management.GetNameResponse")
    public String getName();

    /**
     * 
     * @param name
     */
    @WebMethod
    @RequestWrapper(localName = "setName", targetNamespace = "http://management.people.com", className = "com.people.management.SetName")
    @ResponseWrapper(localName = "setNameResponse", targetNamespace = "http://management.people.com", className = "com.people.management.SetNameResponse")
    public void setName(
        @WebParam(name = "name", targetNamespace = "http://management.people.com")
        String name);

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "getAgeReturn", targetNamespace = "http://management.people.com")
    @RequestWrapper(localName = "getAge", targetNamespace = "http://management.people.com", className = "com.people.management.GetAge")
    @ResponseWrapper(localName = "getAgeResponse", targetNamespace = "http://management.people.com", className = "com.people.management.GetAgeResponse")
    public int getAge();

}
